version: "3.3"
services:
    client:
        image: khouloud123456/movies_client:first
        ports :
            - "3000:3000"
        container_name: client
        depends_on: 
            - server 
        stdin_open: true

    server :
        image: khouloud123456/movies_server:first
        ports: 
            - "3001:3001"
        container_name: server
        depends_on: 
            - database 
    database :
        image: mongo:latest
        ports: 
            - "27017:27017"
        container_name: database
